reroll_threshold = 90
reroll_probability = 2
level_factor = 2
housenumber_factor = 2
exclude_landuse = ["allotments", "commercial", "industrial", "military", "retail"]
exclude_tags = ["amenity", "leisure"]
single_home_list = ["house", "detached"]
apartment_list = ["apartments", "residential"]
unspecified_list = ["terrace", "semidetached_house"]